### ISSUE TITLE
css

### ISSUE THREAD

**Issue by Amodini29** [Amodini29/CBTCIP#2]
```css
body{
    margin: 0;
    font-family: 'Poppins', 'Times New Roman', Times, serif;
    background-color:#baf5e2;
 }
 
 #wrapper h1{
     display:flex;
     justify-content: center;
     
 }
 
 h1{
     color:#d909f5;
     letter-spacing: 1px;
     
 }
 input{
     border-radius: 5px;
     border: 2px solid rgb(10, 10, 10) ;
     margin-top:30px;
     height:2.5em;
     width:250px;
     padding-left:5rem;
 }
 
 input:active{
     border:none;
 }
 #wrapper{
     height:500px;
     width:400px;
     margin:200px auto;
     background-color:#08080b37;
     border-radius:10px;
     padding:30px;
 }
 
 button{
     margin-top:20px;
     background-color:#f7eeee;
     border-radius: 4px;
     height: 30px;
     font-weight: 600;
     padding: 15 30px;
     letter-spacing: 1px;
     border: none;
     color: #102770;
     font-family: 'Poppins', 'Times New Roman', Times, serif;
 }
 
 button:hover{
     cursor:pointer;
 }
 #todoList{
     color:rgb(255, 255, 255);
     font-size:28px;  
     margin-top:10px; 
 }
 
 #todoList p{
   margin:10px 0px;
 }
 
 #todoList p:hover{
   cursor: pointer;
 }
```
