### ISSUE TITLE
css

### ISSUE THREAD

**Issue by Amodini29** [Amodini29/CBTCIP#5]
```css
* General styles */
body {
    font-family: 'Arial', sans-serif;
    margin: 0;
    padding:0;
    line-height: 1.6;
    background-color: #f8f9fa; /* Light gray background */
    color: #343a40; /* Dark gray text */
    max-width: 1200px; /* Wider content */
    margin: 0 auto;
}

/* Header styles */
header {
    background: #199094; /* Dark background */
    color: #040101; /* White text */
    padding: 2rem 0; /* Increased padding */
    text-align: center;
}

header .profile-photo {
    border-radius: 50%;
    width: 150px;
    height: 150px;
    object-fit: cover;
    margin-top: 1rem;
    border: 5px solid #fff; /* White border */
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2); /* Light shadow */
}

header h1 {
    margin: 1rem 0;
    font-size: 3rem; /* Larger font size */
}

header p {
    margin: 0.5rem 0;
    font-size: 1.2rem; /* Slightly larger text */
}

header a {
    color: #8800ff; /* Blue links */
    text-decoration: none;
    margin: 0 1rem;
    transition: color 0.3s ease; /* Smooth color transition */
}

header a:hover {
    color: #0056b3; /* Darker blue on hover */
    text-decoration: underline;
}

/* Main styles */
main {
    padding: 3rem; /* Increased padding */
    max-width: 1200px; /* Wider content */
    margin: 0 auto;
    background: #fff; /* White background */
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.1); /* Slightly stronger shadow */
    border-radius: 8px; /* Rounded corners */
}

section {
    margin-bottom: 3rem; /* Increased spacing between sections */
}

section h2 {
    border-bottom: 2px solid #343a40; /* Dark border bottom */
    padding-bottom: 0.5rem;
    margin-bottom: 2rem; /* Increased margin bottom */
    font-size: 2.5rem; /* Larger heading size */
}

ul {
    list-style-type: none;
    padding: 0;
}

ul li {
    padding: 1rem 0; /* Increased padding */
    font-size: 1.1rem; /* Slightly larger text */
}

ul li strong {
    font-weight: bold;
}

/* Footer styles */
footer {
   
        background: #199094; /* Dark background */
        color: #fff; /* White text */
        text-align: center;
        padding: 2rem 0;
        width: 100%;
        flex-shrink: 0; /* Prevent footer from shrinking */
    
}

```
